@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User #Pink
entity System #darkblue
User -> System: Add Task
System --> User: Add task details
User -> System: Enter task details
System --> User: Confirm Task added successfully


@enduml