@startuml Set Reminder Sequence Diagram
'https://plantuml.com/sequence-diagram

autonumber
actor User #Pink
entity System #darkblue

User -> System: Select a task.
System --> User: Return task details (task name).
User -> System: Select "Set Reminder."
System --> User: Display reminder options (date, time).
User -> System: Enter reminder details and submit.
System --> User: Confirm Reminder is set successfully.
@enduml